---
- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: no


  vars:

  vars_files:
    - ../Creds/F5_creds.yaml

  tasks:
  - name: Create a JIRA issue
    uri:
      url: https://18.133.146.189/mgmt/shared/appsvcs/declare/
      user: "{{user_creds}}"
      password: "{{user_pass}}"
      method: POST
      body: "{{ lookup('file','AS3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no




... 